name: Build Telegram APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Create Fake Local Properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "storeFile=debug.keystore" >> local.properties

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleNoosdebug --no-daemon || ./gradlew assembleDebug --no-daemon
        continue-on-error: true

      - name: Find and Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Telegram-Custom-APK
          path: "**/build/outputs/apk/**/*.apk"
