name: Build Telegram APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Fix Telegram Gradle Settings
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "api_id=123456" >> local.properties
          echo "api_hash=abcdef1234567890abcdef1234567890" >> local.properties
          # Очищаем сломанный файл настроек и пишем туда только базовые модули приложения
          echo "include ':TMessagesProj'" > settings.gradle

      - name: Build Official Telegram APK
        run: |
          chmod +x gradlew
          ./gradlew :TMessagesProj:assembleDebug --no-daemon
